version: "3"

services:
  
  mongo:
    container_name: surf-mongo
    hostname: mongo
    build: './data'
    ports:
      - '27017:27017'
  
  app:
    container_name: surf-app
    hostname: app
    build: './app'
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
    depends_on:
      - mongo