version: '3.7'

services:
  
  app:
    container_name: surf-shop-app
    hostname: app
    build: ./app
    ports:
      - '80:3000'
    volumes:
      - ${PWD}/app:/app
      - /app/node_modules
    depends_on:
      - mongo.data

  mongo.data:
    container_name: surf-shop-mongo
    hostname: mongo
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
  